---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: repositories
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: /opt/yaam/repositories/
