---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: repositories
spec:
  volumeName: repositories
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
