---
name: Yamllint
'on': push
jobs:
  yamllint:
    runs-on: ubuntu-latest
    container:
      image: pipelinecomponents/yamllint:0.22.1
      options: --cpus 1
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: run yamllint
        run: yamllint -c configs/.yamllint.yaml .
